config/routes.rb
Rails.application.routes.draw do
  root "log_entries#index"

  resources :log_entries do
    post "end", on: :member
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/log_entry.rb
# == Schema Information
#
# Table name: log_entries
#
#  id         :integer          not null, primary key
#  ends_at    :datetime
#  content    :string
#  location   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class LogEntry < ApplicationRecord
  after_save :prepend_if_ended
  after_save :update_stats

  def self.active
    now = Time.current
    LogEntry.where(ended_at: nil)
            .where("ends_at > ? AND created_at < ?", now, now)
            .order(ends_at: :desc)
            .limit(1)&.first
  end

  def duration
    if ended_at.nil?
      Time.current - created_at
    else
      ended_at - created_at
    end
  end

  def self.total_duration
    LogEntry.where("created_at > ?", Time.current.beginning_of_day).sum(&:duration)
  end

  def self.total_word_count
    LogEntry.all.sum { |le| le.content&.split&.count || 0 }
  end

  private

    def prepend_if_ended
      return unless saved_change_to_ended_at? && ended_at

      broadcast_prepend_to "log_entries_stream", target: "log_entries"
    end

    def update_stats
      return unless saved_change_to_content?

      broadcast_replace_to "stats_stream",
                           target: "stats",
                           partial: "log_entries/stats"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/log_entries_controller.rb
class LogEntriesController < ApplicationController
  before_action :set_log_entry, only: %i[show update edit end]
  before_action :set_log_entries

  def index
    active = LogEntry.active
    if active
      redirect_to edit_log_entry_path(active)
    else
      @log_entry = LogEntry.new
    end
  end

  def end
    @log_entry.update!(**log_entry_params,
                       ended_at: Time.current)

    redirect_to root_path
  end

  def show; end

  def create
    @log_entry = LogEntry.create!(ends_at: 90.minutes.from_now)
    redirect_to edit_log_entry_path(@log_entry)
  end

  def edit
    @log_entries = @log_entries.reject { |le| le.id == @log_entry.id }
  end

  def update
    @log_entry.update!(log_entry_params)
    head :ok
  end

  private

    def log_entry_params
      params.require(:log_entry).permit(:content)
    end

    def set_log_entry
      @log_entry = LogEntry.find(params[:id])
    end

    def set_log_entries
      @log_entries = LogEntry.order(created_at: :desc).limit(10)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/log_entry_helper.rb
module LogEntryHelper
  def human_duration(duration)
    total_seconds = duration.to_i
    return "00:00:00" if total_seconds <= 0

    hours = total_seconds / 3600
    minutes = (total_seconds / 60) % 60
    seconds = total_seconds % 60

    format("%02d:%02d:%02d", hours, minutes, seconds)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeepWorkLog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="px-8 py-4 border-b border-gray-300 bg-gray-100">
      <p class="text-slate-700 font-light">DeepWorkLog</p>
    </div>

    <main class="container mx-auto mt-12 mb-28 px-5 flex max-w-[60ch] flex-col space-y-12">
      <%= turbo_stream_from "stats_stream" %>
      
      <%= render partial: "stats" %>

      <%= yield %>

      <%= render partial: "log_entries/all", locals: { log_entries: @log_entries } %>
    </main>
  </body>
</html>

app/views/log_entries/_all.html.erb
<%= turbo_stream_from "log_entries_stream" %>

<div class="flex flex-col space-y-12" id="log_entries">
  <% @log_entries.each do |entry| %>
    <%= render entry %>
  <% end %>
</div>

app/views/log_entries/_log_entry.html.erb
<div id="<% dom_id log_entry %>" class="fade-in">
  <div class="relative flex flex-col space-y-2">
    <p class="absolute z-10 top-[0rem] left-[1rem] bg-white text-xs text-gray-600 px-2">
      <%= log_entry.created_at.strftime('%Y-%m-%d %H:%M') %> (<%= time_ago_in_words(log_entry.created_at) %> ago)
    </p>
    <p class="absolute z-10 top-[1rem] right-[1rem] bg-green-100 text-xs text-green-600 rounded px-2 py-1">
      <%= human_duration(log_entry.duration) %>
    </p>
    <div class="border p-12 border-gray-600 rounded text-gray-500 shadow">
      <%= log_entry.content&.gsub(/\r?\n/, "<br>")&.html_safe %>
    </div>
  </div>
</div>

app/views/log_entries/_remaining.html.erb
<div class="absolute top-[1rem] right-[1rem] text-sm z-10 bg-gray-100 px-2 py-2 rounded"
  data-controller="countdown"
  data-countdown-countdown-to-value="<%= log_entry.ends_at %>"
>
  <span
    data-countdown-target="clock"
  ><%= human_duration(log_entry.ends_at - Time.current) %></span> remaining
</div>

app/views/log_entries/_stats.html.erb
<div class="flex flex-row space-x-8 justify-between items-center" id="stats">
  <div class="flex flex-col p-12 border border-gray-300 rounded shadow">
    <p class="text-xl"><%= LogEntry.total_word_count %></p>
    <p>words written</p>
  </div>
  <div class="flex flex-col p-12 border border-gray-300 rounded shadow">
    <p class="text-xl"><%= human_duration(LogEntry.total_duration) %></p>
    <p>time spent focused today</p>
  </div>
</div>

app/views/log_entries/_stats_wc.html.erb
<div class="flex flex-col p-12 border border-gray-300 rounded shadow" id="stats_wc">
  <p class="text-xl"><%= LogEntry.total_word_count %></p>
  <p>words written</p>
</div>

app/views/log_entries/create.html.erb
<div>
  <h1 class="font-bold text-4xl">LogEntry#create</h1>
  <p>Find me in app/views/log_entry/create.html.erb</p>
</div>

app/views/log_entries/edit.html.erb
<%= turbo_frame_tag "active_entry" do %>
  <div
    id="<%= dom_id(@log_entry, :edit) %>"
    data-controller="loading auto-save"
    data-auto-save-url-value="<%= log_entry_path(@log_entry) %>"
    class="relative w-full">

    <div data-loading-target="swap"  class="relative flex flex-col space-y-4 w-full">
    <%= render partial: "remaining",
               locals: { log_entry: @log_entry } %>

    <%= form_with model: @log_entry, method: :post, url: end_log_entry_path(@log_entry), class: "w-full", data: { "action" => "loading#swapToLoading" } do |f| %>
      <%= f.text_area :content,
       class: "w-[55ch] mb-8 snap-open",
       data: { "action" => "keydown.space->auto-save#save" },
       autofocus: true %>
      <%= f.submit "End session", class: "w-full px-2 py-4 rounded border border-gray-800", data: {
        "turbo-action" => "advance",
      } %>
    <% end %>
    </div>
  </div>
<% end %>

app/views/log_entries/index.html.erb
<%= turbo_frame_tag "active_entry" do %>
  <div
    class="flex items-center justify-center"
    data-controller="loading"
  >
    <%= form_with model: @log_entry, data: {
      "action" => "submit->loading#swapToLoading",
      "loading-target" => "swap"
    },
     class: "w-full" do |f| %>
      <%= f.submit "Start 90min session",
       data: { "turbo-action" => "advance" },
       class: "border w-full px-4 py-4 rounded border-gray-800 bg-gray-800 text-white shadow hover:shadow-lg cursor-pointer" %>
    <% end %>
  </div>
<% end %>

app/views/log_entries/new.html.erb
<div>
  <h1 class="font-bold text-4xl">LogEntry#new</h1>
  <p>Find me in app/views/log_entry/new.html.erb</p>
</div>

app/views/log_entries/show.html.erb
<div>
  <h1 class="font-bold text-4xl">LogEntry#show</h1>
  <p>Find me in app/views/log_entry/show.html.erb</p>
</div>

app/views/log_entries/update.html.erb
<div>
  <h1 class="font-bold text-4xl">LogEntry#update</h1>
  <p>Find me in app/views/log_entry/update.html.erb</p>
</div>